FROM ubuntu:bionic

ARG UID=1000
ARG GID=1000

RUN apt-get update && apt-get -y upgrade && apt-get -y install \
	build-essential \
	cmake

RUN groupadd -g $GID -o notroot &&  useradd -c 'unprivileged user' -u $UID -g $GID -o -m -d /home/notroot -s /bin/bash notroot
USER notroot

